name       : yosys
version    : 0.13
release    : 11
source     :
    - https://github.com/YosysHQ/yosys/archive/yosys-0.13.tar.gz : 004c203cb516887a8c76678a1fd76381198a8c46a17f4d893c34b7521df894b5
    - git|https://github.com/berkeley-abc/abc : 2ddc57d8760d94e86699be39a628178cff8154f8
license    : ISC
component  : office.scientific
summary    : Yosys Open SYnthesis Suite
description: |
    Yosys is a framework for Verilog RTL synthesis. It currently
    has extensive Verilog-2005 support and provides a basic set of
    synthesis algorithms for various application domains.
patterns   :
    - devel :
        - /usr/bin/yosys-config
        - '%libdir%/libyosys.so'
        - /usr/share/yosys/include
builddeps  :
    - git
    - iverilog
    - pkgconfig(libffi)
    - pkgconfig(python3)
    - pkgconfig(tcl)
    - libboost-devel
setup      : |
    cp -a $sources/abc.git abc
    make ABCREV=default PREFIX=/usr config-gcc
    sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
    echo "PREFIX=/usr"          >> Makefile.conf
    echo "LIBDIR=%libdir%"      >> Makefile.conf
    echo "ENABLE_LIBYOSYS=1"    >> Makefile.conf
    echo "ENABLE_PYOSYS=1"      >> Makefile.conf
    echo "PYTHON_DESTDIR=${sitedir}" >> Makefile.conf
build      : |
    %make ABCREV=default BOOST_PYTHON_LIB="-lpython3.9 -lboost_python39"
check      : |
    (cd tests/simple  && bash run-test.sh)
    (cd tests/fsm     && bash run-test.sh)
    (cd tests/svtypes && bash run-test.sh)
    (cd tests/verilog && bash run-test.sh)
install    : |
    %make_install ABCREV=default
    # remove redundant copy of .so file
    rm -f $installdir/usr/bin/*.so

