name       : yosys
version    : 0.8
release    : 1
source     :
    - https://github.com/YosysHQ/yosys/archive/yosys-0.8.tar.gz : 07760fe732003585b26d97f9e02bcddf242ff7fc33dbd415446ac7c70e85c66f
    - git|https://github.com/berkeley-abc/abc : ae6716b064c842f45109a88e84dca71fe4cc311f
license    : ISC
component  : office.scientific
summary    : Yosys Open SYnthesis Suite
description: |
    Yosys is a framework for Verilog RTL synthesis. It currently
    has extensive Verilog-2005 support and provides a basic set of
    synthesis algorithms for various application domains.
builddeps  :
    - git
    - iverilog
    - pkgconfig(libffi)
    - pkgconfig(python3)
    - pkgconfig(tcl)
    - libboost-devel
setup      : |
    cp -a $sources/abc.git abc
    make ABCREV=default PREFIX=/usr config-gcc
build      : |
    %make ABCREV=default PREFIX=/usr
check      : |
    make -j %YJOBS% ABCREV=default PREFIX=/usr test
install    : |
    %make_install ABCREV=default PREFIX=/usr

