name       : yosys
version    : 0.9
release    : 10
source     :
    - https://github.com/YosysHQ/yosys/archive/yosys-0.9.tar.gz : f2e31371f9cf1b36cb4f57b23fd6eb849adc7d935dcf49f3c905aa5136382c2f
    - git|https://github.com/berkeley-abc/abc : 2ddc57d8760d94e86699be39a628178cff8154f8
license    : ISC
component  : office.scientific
summary    : Yosys Open SYnthesis Suite
description: |
    Yosys is a framework for Verilog RTL synthesis. It currently
    has extensive Verilog-2005 support and provides a basic set of
    synthesis algorithms for various application domains.
patterns   :
    - devel :
        - /usr/bin/yosys-config
        - '%libdir%/libyosys.so'
        - /usr/share/yosys/include
builddeps  :
    - git
    - iverilog
    - pkgconfig(libffi)
    - pkgconfig(python3)
    - pkgconfig(tcl)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/gcc11.patch
    cp -a $sources/abc.git abc
    make ABCREV=default PREFIX=/usr config-gcc
    sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
    echo "PREFIX=/usr"          >> Makefile.conf
    echo "LIBDIR=%libdir%"      >> Makefile.conf
    echo "ENABLE_LIBYOSYS=1"    >> Makefile.conf
    echo "ENABLE_PYOSYS=1"      >> Makefile.conf
    echo "PYTHON_DESTDIR=$installdir/${sitedir}" >> Makefile.conf
build      : |
    %make ABCREV=default BOOST_PYTHON_LIB="-lpython3.9 -lboost_python39"
check      : |
    make -j %YJOBS% ABCREV=default
install    : |
    %make_install ABCREV=default
    # remove redundant copy of .so file
    rm -f $installdir/usr/bin/*.so

